FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    software-properties-common \
    openssh-server \
    python3 \
    python3-pip \
    sshpass \
    curl \
    wget \
    vim \
    git \
    sudo \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install ansible ansible-lint

RUN useradd -m -s /bin/bash ansible && \
    echo "ansible:ansible" | chpasswd && \
    echo "ansible ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

RUN mkdir /var/run/sshd && \
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config

RUN mkdir -p /home/ansible/ansible /home/ansible/artifacts && \
    chown -R ansible:ansible /home/ansible

WORKDIR /home/ansible

USER ansible

CMD ["/bin/bash"]

