---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Copy Nginx default configuration
  ansible.builtin.template:
    src: default.conf
    dest: /etc/nginx/sites-available/default
  notify:
    - Reload Nginx

- name: Ensure Nginx service is running and enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes